extraction:
  cpp:
    prepare:
      packages: 
        - libpcre3-dev
        - libssl-dev
        - zlib1g-dev
        - libzstd-dev
        - libc6-dev
        - libpng-dev
        - libjpeg-dev
        - libtiff-dev
        - libcups2-dev
        - libfreetype6-dev
        - libfontconfig1-dev
        - libdbus-1-dev
        - libicu-dev
        - unixodbc-dev
        - libpq-dev
        - libpqtypes-dev
        - libmariadbd-dev
        - libaio-dev
        - libwrap0-dev
        - liblz4-dev
        - libsqlite3-dev
        - libunwind-dev
        - xorg-dev
