sudo: required
dist: trusty
language: cpp
compiler:
    - clang
    - gcc
os:
    - linux
cache: ccache
git:
    depth: 3
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq bsdtar python-dev libssl-dev zlib1g-dev libc6-dev libpng12-dev libjpeg-dev libtiff5-dev libmng-dev libcups2-dev libasound2-dev libfreetype6-dev libfontconfig1-dev libicu-dev libglib2.0-dev libdbus-1-dev libgtk2.0-dev libgl1-mesa-dev libwayland-dev unixodbc-dev libpq-dev libmysqld-dev libaio-dev libsqlite3-dev xorg-dev
    - wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip
    - bsdtar xf ninja-linux.zip
before_script:
    - export PATH="$(pwd):${PATH}"
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3
script:
    - if [ "$CXX" == "clang++" ];then cmake -GNinja -DENABLE_TESTING=TRUE -DKATIE_UTILS=ON -Wno-dev -DMYSQL_LIBRARIES:STRING="-lmysqld -lcrypt -laio" ;fi
    - if [ "$CXX" == "g++" ];then cmake -GNinja -DENABLE_TESTING=TRUE -DKATIE_UTILS=ON -DKATIE_ALLINONE=ON -Wno-dev -DMYSQL_LIBRARIES:STRING="-lmysqld -lcrypt -laio" ;fi
    - ninja
# the tests/benchmarks take more then 1-hour and Travis times out,
# despite the documentaiton for the service claiming otherwise
