sudo: required
dist: xenial
language: cpp
compiler:
    - clang
    - gcc
os:
    - linux
cache: ccache
git:
    depth: 3
before_install:
    - sudo apt-get update -qq
# trusty
#    - sudo apt-get install -qq bsdtar python-dev libpcre3-dev libssl-dev zlib1g-dev libc6-dev libpng12-dev libjpeg-dev libtiff5-dev libmng-dev libcups2-dev libfreetype6-dev libfontconfig1-dev libicu-dev libglib2.0-dev libdbus-1-dev unixodbc-dev libpq-dev libmysqld-dev libaio-dev libwrap0-dev libsqlite3-dev xorg-dev
#    - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
#    - bsdtar xf ninja-linux.zip
# xenial
    - sudo apt-get install -qq bsdtar python-dev libpcre3-dev libssl-dev zlib1g-dev libc6-dev libpng-dev libjpeg-dev libtiff-dev libmng-dev libcups2-dev libfreetype6-dev libfontconfig1-dev libicu-dev libglib2.0-dev libdbus-1-dev unixodbc-dev libpq-dev libmysqld-dev libaio-dev libwrap0-dev libsqlite3-dev xorg-dev
before_script:
    - export PATH="$(pwd):${PATH}"
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3
script:
    - mkdir build && cd build
    - if [ "$CXX" == "clang++" ];then cmake ../ -GNinja -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTING=TRUE -DKATIE_UTILS=ON -Wno-dev ;fi
    - if [ "$CXX" == "g++" ];then cmake ../ -GNinja -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTING=TRUE -DKATIE_UTILS=ON -DKATIE_ALLINONE=ON -Wno-dev ;fi
    - ninja
# the tests/benchmarks take more then 1-hour and Travis times out,
# despite the documentaiton for the service claiming otherwise
