sudo: required
dist: bionic
language: cpp
compiler:
    - clang
    - gcc
os:
    - linux
cache: ccache
git:
    depth: 3
services:
    - xvfb
    - mysql
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq ninja-build libpcre3-dev libssl-dev zlib1g-dev libzstd-dev libc6-dev libpng-dev libjpeg-dev libtiff-dev libmng-dev libcups2-dev libfreetype6-dev libfontconfig1-dev libdbus-1-dev libicu-dev unixodbc-dev libpq-dev libpqtypes-dev libmysqld-dev libaio-dev libwrap0-dev liblz4-dev libsqlite3-dev libunwind-dev xorg-dev
script:
    - mkdir build && cd build
    - if [ "$CXX" == "clang++" ];then cmake ../ -GNinja -DCMAKE_BUILD_TYPE=Release -DKATIE_TESTS=ON -DKATIE_BENCHMARKS=ON -DKATIE_UTILS=ON -Wno-dev ;fi
    - if [ "$CXX" == "g++" ];then cmake ../ -GNinja -DCMAKE_BUILD_TYPE=Debug -DKATIE_TESTS=ON -DKATIE_ALLINONE=ON -Wno-dev ;fi
    - ninja
    - if [ "$CXX" == "g++" ];then ctest -V ;fi
