sudo: required
dist: bionic
language: cpp
compiler:
    - clang
    - gcc
os:
    - linux
arch:
    - amd64
    - arm64
    - ppc64le
    - s390x
cache:
    apt: true
    ccache: true
    packages: true
git:
    depth: 3
services:
    - dbus
    - xvfb
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq ninja-build libpcre3-dev libssl-dev zlib1g-dev libzstd-dev libc6-dev libpng-dev libjpeg-dev libtiff-dev libcups2-dev libfreetype6-dev libfontconfig1-dev libdbus-1-dev libicu-dev unixodbc-dev libpq-dev libsqlite3-dev xorg-dev
script:
    - mkdir build && cd build
    - if [ "$CXX" == "clang++" ];then cmake ../ -GNinja -DCMAKE_BUILD_TYPE=Release -DKATIE_TESTS=ON -DKATIE_BENCHMARKS=ON -DKATIE_UTILS=ON -DWITH_MYSQL=OFF -Wno-dev ;fi
    - if [ "$CXX" == "g++" ];then cmake ../ -GNinja -DCMAKE_BUILD_TYPE=Debug -DKATIE_TESTS=ON -DKATIE_ALLINONE=ON -DWITH_MYSQL=OFF -Wno-dev ;fi
    - ninja
    - if [ "$CXX" == "g++" ];then ctest -V ;fi
