language: cpp
compiler:
    - clang
#    - gcc
git:
    depth: 3
# https://raw.githubusercontent.com/travis-ci/apt-package-whitelist/master/ubuntu-precise
addons:
  apt:
    packages:
    - cmake
    - python-dev
    - libssl-dev
    - zlib1g-dev
    - libc6-dev
    - libpng-dev
    - libjpeg-dev
    - libtiff5-dev
    # - libmng-dev
    - libcups2-dev
    - libasound2-dev
    - libfreetype6-dev
    - libfontconfig1-dev
    - libicu-dev
    - libglib2.0-dev
    # - libdbus-1-dev
    - libgtk2.0-dev
    - libgl1-mesa-dev
    # - libwayland-dev
    - unixodbc-dev
    - libpq-dev
    - libmysqld-dev
    - libaio-dev
    - libsqlite3-dev
    - xorg-dev
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
script:
    - cmake -DENABLE_TESTING=TRUE -Wno-dev -DMYSQL_LIBRARIES:STRING="-lmysqld -lcrypt -laio"
    - make
    - make test
