version: 4.9.2-{branch}-{build}
image: Ubuntu2004
clone_depth: 1
services:
  - mysql
  - postgresql

build_script:
- sh: >-
    sudo apt-get update -qq

    sudo apt-get install -qq libpcre3-dev libssl-dev zlib1g-dev libzstd-dev libc6-dev libpng-dev \
        libjpeg-dev libtiff-dev libcups2-dev libfreetype6-dev libfontconfig1-dev libdbus-1-dev \
        libicu-dev unixodbc-dev libpq-dev libmariadbclient-dev libmariadbd-dev liblz4-dev \
        libsqlite3-dev xorg-dev dbus-x11

    cmake . -Wno-dev -DKATIE_TESTS=ON -DKATIE_BENCHMARKS=ON -DKATIE_UTILS=ON -DKATIE_PCH=ON -DCMAKE_UNITY_BUILD=ON

    make -j $(nproc || echo 1)

test_script:
- sh: >-
    Xvfb :123 &

    export DISPLAY=:123

    cd tests/auto

    ctest -V
