version: 4.12.0-{branch}-{build}
image: Ubuntu2004
clone_depth: 1
cache:
  - /home/appveyor/.ccache

build_script:
- sh: >-
    git log > /tmp/gitlog.txt

    grep -q '\[ci reset\]' /tmp/gitlog.txt && rm -rf /home/appveyor/.ccache

    sudo apt-get update -qq

    sudo apt-get install -qq libdeflate-dev libc6-dev \
        libpng-dev libcups2-dev libfreetype6-dev libfontconfig1-dev \
        libdbus-1-dev libicu-dev xorg-dev dbus-x11 libjansson-dev ccache \
        fonts-freefont-ttf

    export PATH="/usr/lib/ccache/:$PATH"

    python ./scripts/cicount.py

    cmake . -Wno-dev -DKATIE_TESTS=ON -DKATIE_BENCHMARKS=ON -DKATIE_UTILS=ON

    make -j $(nproc || echo 1)

test_script:
- sh: >-
    Xvfb :123 &

    export DISPLAY=:123

    cd tests/auto

    ctest -V
